### PR TITLE
Doc Update

### PR DESCRIPTION
**Pull request by hasnainvirk**
* Instructions updated to view resources in connector.
* Multiple platform support section removed as it is not valid anymore.

### CODE REVIEW

**Comment by hasnainvirk** [comment]
@SeppoTakalo @yogpan01 

Please review

**Comment by peknis01** [comment]
Do you need my input?

**Comment by SeppoTakalo** [comment]
@peknis01 Yes please.

**Comment by peknis01** [comment]
Should be ok now.

**Pull request merged**
