### PR TITLE
Add support for Ublox Odin board

### PR DESCRIPTION
**Pull request by bulislaw**
That wasn't really tested due to: https://github.com/ARMmbed/oob-mbed-os-example-client/issues/1 also it required Ublox proprietary library, which haven't been merged to mbed yet.

### CODE REVIEW

**Comment by yogpan01** [comment]
@0xc0170 No proposal yet. Frankly I dont have time for this now.

**Comment by andcor02** [comment]
Is this possible to get running on the EVK-ODIN-W2 now?

Andrea

**Comment by bulislaw** [comment]
Odin support is part of mbed-os now and the ESP sha was updated as part of RC. I think it's ready to merge.

**Comment by andcor02** [comment]
@bulislaw 

I get the following error #13

**Comment by bulislaw** [comment]
It works for me (using both gcc 4.9 and 5.4)...

**Comment by bulislaw** [comment]
Ah no sorry, I'm having the same issue (forgot to set WIFI in the config).

**Comment by bulislaw** [comment]
@andcor02 Could you try removing this line from mbed_app.json
```
-    "macros": ["MBEDTLS_USER_CONFIG_FILE=\"mbedtls_mbed_client_config.h\""],
```

**Comment by bulislaw** [comment]
OK I don't know what happened here, I'll open another PR.

**Pull request closed without merging**
